### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by arrrrrmin** [KnowKit/convmoji#2]
Return a proper error code for unknown conv-tags (emoji is not mappable when using wrong tag)

Since `0.1.7` also:
```
? Your commit message (required)                                                                                      

Cancelled by user

Traceback (most recent call last):
  File "/usr/local/bin/convmoji", line 8, in <module>
    sys.exit(app())
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1052, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 914, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1370, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2347, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 2309, in process_value
    value = self.callback(ctx, self, value)
  File "/usr/local/lib/python3.10/site-packages/typer/main.py", line 802, in wrapper
    return callback(**use_params)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/convmoji/commit.py", line 136, in interactive_mode
    answers["type"] = answers["type"].split(":")[0]
KeyError: 'type'
```

**Comment by arrrrrmin** [comment]
fixed in `0.1.7a0`
